name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
      - '**'
    tags:
      - 'release-candidate'

defaults:
  run:
    shell: bash

jobs:
  cleanup:
    runs-on: ubuntu-20.04
    steps:
      - name: Clean Up Release Candiate Tag
        if: ${{ github.ref == 'refs/tags/release-candidate' }}
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: release-candidate
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  all:
    runs-on: ubuntu-20.04
    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: browser-actions/setup-chrome@latest
      - name: Setup environment
        run: |
          make env.up
      # Build and Test
      - name: Run CI jobs
        run: |
          make ci
      # Publish documentation
      - name: Set default env variables
        run: |
          echo "GH_PAGES_BRANCH=gh-pages-test" >> $GITHUB_ENV
      - name: Update env variables for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "GH_PAGES_BRANCH=gh-pages" >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          target_branch: ${{ env.GH_PAGES_BRANCH }}
          build_dir: gh-pages-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Release
      - name: Check Commit Messages
        run: |
          release check-commit-messages
      - name: Generate Changelog
        run: |
          release changelog > changelog.md
      - name: Delete Previous Master Github Release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: master
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Master Github Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          gh release create master ./dist/*.whl -F changelog.md --prerelease --target master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Github Release
        if: ${{ github.ref == 'refs/tags/release-candidate' }}
        run: |
          gh release create v`release version` ./dist/*.whl -F changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish PyPI
        if: ${{ github.ref == 'refs/tags/release-candidate' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          skip_existing: false
